name: Scrape DMV Wait Times

on:
  schedule:
    - cron: '*/15 18-19 * * *'  # Every 15 minutes, 2 to 3 pm. For science.
    # - cron:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print UTC time
        run: date -u

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run scraper
        env: 
          GOOGLE_CREDS_B64: ${{ secrets.GOOGLE_CREDS_B64 }}
        run: |
          python scraper.py

