# - name: Show structure
#   run: ls -R
  # working directory: dmv_scraper


name: Scrape DMV Wait Times

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    # working directory: dmv_scraper

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Check directory structure
      run: ls -R

    - name: Install dependencies
      run: pip install --upgrade --force-reinstall -r requirements.txt
      working-directory: ./
      
      
    - name: Run scraper
      # working directory: dmv_scraper
      env:
        GOOGLE_CREDS_B64: ${{ secrets.GOOGLE_CREDS_B64 }}
      run: python scraper.py
      working-directory: ./
